# Copyright 2018 Cargill Incorporated
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM rust:1.22.1

RUN apt-get update && apt-get install -y unzip libzmq3-dev

# For Building Protobufs
RUN curl -OLsS https://github.com/google/protobuf/releases/download/v3.5.1/protoc-3.5.1-linux-x86_64.zip \
 && unzip protoc-3.5.1-linux-x86_64.zip -d protoc3 \
 && rm protoc-3.5.1-linux-x86_64.zip
RUN apt-get update && apt-get install -y protobuf-compiler

# Copy protos directory
COPY protos/ /sawtooth-supply-chain/protos/

WORKDIR /sawtooth-supply-chain/processor/supply_chain_rust

# Copy everything except the target directory from the TP source
COPY processor/supply_chain_rust/Cargo.toml processor/supply_chain_rust/build.rs ./
COPY processor/supply_chain_rust/src/ src/
RUN cargo build

ENV PATH=$PATH:/sawtooth-supply-chain/processor/supply_chain_rust/target/debug/

ENTRYPOINT ["/sawtooth-supply-chain/processor/supply_chain_rust/target/debug/supply_chain_rust"]
